cd config/yolov4/
wget https://hobbitdata.informatik.uni-leipzig.de/VEP/models/256.zip
wget https://hobbitdata.informatik.uni-leipzig.de/VEP/models/416.zip
wget https://hobbitdata.informatik.uni-leipzig.de/VEP/models/448.zip
wget https://hobbitdata.informatik.uni-leipzig.de/VEP/models/512.zip
wget https://hobbitdata.informatik.uni-leipzig.de/VEP/models/672.zip
wget https://hobbitdata.informatik.uni-leipzig.de/VEP/models/832.zip
wget https://hobbitdata.informatik.uni-leipzig.de/VEP/models/tiny.zip
unzip 256.zip
unzip 416.zip
unzip 512.zip
unzip 832.zip
unzip tiny.zip
rm 256.zip
rm 416.zip
rm 512.zip
rm 832.zip
rm tiny.zip

